### ISSUE TITLE
Conda lock can hang, clearing poetry cache helps

### ISSUE THREAD

**Issue by mattkram** [conda-incubator/conda-project#103]
Using `conda-project=0.1.1`, my system was stuck during `conda project lock` with the following environment file:

```yaml
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - planingfsi
platforms:
  - osx-64
  - osx-arm64
  - linux-64
```

I found that clearing the poetry cache helped to resolve the issue: `poetry cache clear pypi --all`

I'm wondering if we should consider any special behavior or warning if this becomes a more common occurrence.
