### ISSUE TITLE
Incorrect console message when running `conda project lock`

### ISSUE THREAD

**Issue by mattkram** [conda-incubator/conda-project#104]
When running `conda project lock` with the following environment, the console message is incorrect. It lists all platforms, instead of the ones specified (in this case, the message should not include `win-64`).

```yaml
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - planingfsi
platforms:
  - osx-64
  - osx-arm64
  - linux-64
```

```shell
❯ conda project lock
Locking dependencies for environment default on platforms osx-arm64, linux-64, win-64, osx-64: done
```

The generated lockfile is correct:

```
metadata:
  channels:
  - url: defaults
    used_env_vars: []
  content_hash:
    linux-64: 3b64bba63adc0519d1ce307aed78149b9df05a9e4431285368d28c3e32fab703
    osx-64: 4f4777149b9b210511505bfd4d26cf85a2b2738b6e9a7a5dc49136bc5706aebe
    osx-arm64: c3c3d9bdd6da8961c01b2fc54a4cec463bd7b387721175b24e521731203aae56
  platforms:
  - osx-64
  - osx-arm64
  - linux-64
...
```
