### ISSUE TITLE
Support remote environment definitions

### ISSUE THREAD

**Issue by AlbertDeFusco** [conda-incubator/conda-project#127]
It would great to enable remote sources for environments

```yaml
name: my-project

environments:
  not-locked-env:
    - <protocol>://<path>/<to>/<environment-yaml>[?param1=value&param2=value]
  pre-locked-env:
    - <protocol>://<path>/<to>/<conda-lock-yaml>[?param1=value&param2=value] 
```

In the first env `not-locked-env` the remote definition is the intentional spec and the lockfile will be computed and stored locally.

In the second environment the remote definition is to the lockfile. Here we would not need to run conda-lock locally or store the file locally.
