### ISSUE TITLE
Environment is always inconsistent: missing sha256

### ISSUE THREAD

**Issue by AlbertDeFusco** [conda-incubator/conda-project#130]
For the following environment.yaml the installed env is always inconsistent

```yaml
❯ cat environment.yml
dependencies:
  - ctools::pydantic-yaml
channels:
  - defaults
  - conda-forge
```

The problem appears to come from a missing sha256 for pydantic-yaml

<img width="898" alt="Screenshot 2023-07-24 at 14 28 53" src="https://github.com/conda-incubator/conda-project/assets/43654/2855bbdc-380f-4a29-bc83-d91e0d47380f">
