### ISSUE TITLE
"conda project add" completely override project files

### ISSUE THREAD

**Issue by JeanChristopheMorinPerso** [conda-incubator/conda-project#174]
Let's say I have a project file that looks like this:

```yaml
dependencies:
# renovate: datasource=conda depName=main/sqlalchemy
- sqlalchemy=2.0.34
platforms:
  - linux-64
channels:
  - defaults
```

If I run `conda project add orjson=3.10.7`, the resulting file will look like

```yaml
dependencies:
- sqlalchemy=2.0.34
- orjson=3.10.7
platforms:
  - linux-64
channels:
  - defaults
```
It stripped the comments. Not only that, but it also doesn't keep the entries sorted like the original file. This is not very convenient.

`conda project add` should keep the comments and the order as it is.
