### ISSUE TITLE
[ENH] Run a configured command with the local environment

### ISSUE THREAD

**Issue by AlbertDeFusco** [conda-incubator/conda-project#2]
# The need

A user has an environment.yml file and wants to specify a command that can be run with this project. The user would like to declare this command in a YAML file

```yaml
name: my-project

dependencies:
  - python=3.8
  - tranquilizer
  - pip
  - pip:
    - requests

variables:
  FOO: bar
```

# What to expect

The user can write a `conda-project.yml` file declaring one or more commands. Nice-to-have: Jinja2 templating for standard things like port number.

```yaml
commands:
  default:
    cmd: tranquilizer api.py
    env_spec: default # this is the default value and not required in the project file
```

And execute the command

```
conda project run [default]
...
```

The environment will be prepared first if the user has not already done so.
