### ISSUE TITLE
[ENH] Lock project dependencies

### ISSUE THREAD

**Issue by AlbertDeFusco** [conda-incubator/conda-project#3]
## The need

The user has an environment.yml file specifying the minimal dependencies and the supported platforms. The user would like to have a fully-locked specification of the dependencies to ensure reproducibility for each platform.

```yaml
name: my-project

dependencies:
  - python=3.8
  - tranquilizer
  - pip
  - pip:
    - requests

variables:
  FOO: bar

platforms:
  - osx-64
  - osx-arm64
  - linux-64
  - win-64
```

## What to expect

The user runs a command to create a `conda-lock.yml` file locking dependencies for all platforms listed in the environment.yml (or a default set if not specified).

```
conda project lock
```

If a hash of the environment.yml file changes against one captured in the `conda-lock.yml` file commands like `prepare` and `run` should issue a warning.

## Open questions

* When a user adds dependencies to the environment.yml file and runs lock a second time should the full environment be re-solved or use a procedure like Conda's `--freeze-installed` to keep the previously locked dependencies where they are?
* When running lock (without changes to the environment.yml file) should it re-lock the dependencies from scratch or do nothing? (anaconda-project uses `update` to re-lock)
