### ISSUE TITLE
Pep517 and pep518

### ISSUE THREAD

**Issue by AlbertDeFusco** [conda-incubator/conda-project#59]
What if the contents of the project is a python package with a defined build system such that `pip install .` is meant to call poetry. 

My intention is that conda-project can be the provider of Python, compilers, and other system-level tools for the package to compile. The environment.yml might look like

```yaml
dependencies:
  - python=3.8
  - c++ # the appropriate name of this compiler to be determined
  - pip:
    - .
```
