### ISSUE TITLE
[ENH] Multiple conda environments

### ISSUE THREAD

**Issue by AlbertDeFusco** [conda-incubator/conda-project#6]
The environment.yml file specification currently only supports one env. We can use multiple yaml files combined with environment specification in `conda-project.yml` to be able to maintain and extend multiple environments in a single project.

```yaml
commands:
  server:
    cmd: ...
    env_spec: default
  test:
    cmd: pytest
    env_spec: test

env_specs:  
  default:
    filename: environment.yml  # default behavior
  test:
    filename: environment-test.yml
  dev:
    filename: environment-test.yml
    dependencies:
    - notebook
    - ...
```
