### ISSUE TITLE
pre-load intake catalog as builtin catalog

### ISSUE THREAD

**Issue by AlbertDeFusco** [conda-incubator/conda-project#70]
The scenario

```yaml
environments:
  default:
    - environment.yml
catalogs:
  - https://....yaml
```

What do we have to do get this to work where the catalog is automatically loaded?

```python
import intake

intake.gui
```
