### ISSUE TITLE
Lock and prepare with local package

### ISSUE THREAD

**Issue by AlbertDeFusco** [conda-incubator/conda-project#83]
When attempting to install a python package local to the project conda-lock warns that the package will not be added to the lockfile.

I think there should be a way for conda-project to handle this scenario.

```yaml
# envnironment.yml

dependencies:
  - python=3.9
  - pip
  - pip:
    - . # optionally include -e
```

Should conda-project be more forceful in ensuring that the dependencies of the local package are locked?
